//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Root
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Root()
        {
            this.Root1 = new HashSet<Root>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Word { get; set; }
        public bool Grouped { get; set; }
        public Nullable<bool> VocabularyCom { get; set; }
        public Nullable<bool> DictionaryCom { get; set; }
        public Nullable<int> VocabularyComStatusCode { get; set; }
        public Nullable<int> DictionaryComStatusCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string VocabularyWordFamilyJson { get; set; }
        public string DictionaryWordFamily { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> RankFromPaymon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Root> Root1 { get; set; }
        public virtual Root Root2 { get; set; }
    }
}
