//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiktionary
    {
        public long Id { get; set; }
        public string Word { get; set; }
        public string ParentLanguageName { get; set; }
        public string LanguageName { get; set; }
        public string Code { get; set; }
        public string Category { get; set; }
        public string Priority { get; set; }
        public string Translated { get; set; }
        public string TransSee { get; set; }
    }
}
