//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnglishWordsEntities : DbContext
    {
        public EnglishWordsEntities()
            : base("name=EnglishWordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllWordFromPaymon> AllWordFromPaymons { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<WordTranslate> WordTranslates { get; set; }
        public virtual DbSet<Joke> Jokes { get; set; }
        public virtual DbSet<Phonetic> Phonetics { get; set; }
    
        public virtual ObjectResult<GetWordForTranslate_Result> GetWordForTranslate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetWordForTranslate_Result>("GetWordForTranslate");
        }
    
        public virtual ObjectResult<GetCompletedLanguages_Result> GetCompletedLanguages()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompletedLanguages_Result>("GetCompletedLanguages");
        }
    
        public virtual ObjectResult<string> GetJsonFile(Nullable<int> languageId)
        {
            var languageIdParameter = languageId.HasValue ?
                new ObjectParameter("LanguageId", languageId) :
                new ObjectParameter("LanguageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetJsonFile", languageIdParameter);
        }
    
        public virtual ObjectResult<GetJokeBest_Result> GetJokeBest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJokeBest_Result>("GetJokeBest");
        }
    }
}
