//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordTranslate
    {
        public int WordID { get; set; }
        public int LanguageId { get; set; }
        public string Translated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
