//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WordCombination
    {
        public string Word1 { get; set; }
        public string Word2 { get; set; }
        public int Count { get; set; }
        public int Rank { get; set; }
    }
}
