//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWordProcess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishWordsEntities : DbContext
    {
        public EnglishWordsEntities()
            : base("name=EnglishWordsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Root> Roots { get; set; }
        public virtual DbSet<WordInType> WordInTypes { get; set; }
        public virtual DbSet<WordType> WordTypes { get; set; }
        public virtual DbSet<RankAndCount> RankAndCounts { get; set; }
        public virtual DbSet<WordFromPaymon> WordFromPaymons { get; set; }
        public virtual DbSet<WordCombination> WordCombinations { get; set; }
    }
}
